### ISSUE TITLE
YouTube play/pause button in a random state after page load

### ISSUE THREAD

**Issue by legovini** [Eloston/disable-html5-autoplay#1]
Hello,

first of all thanks for developing this extension, it might be the first sane autoplay blocker available. What I'm reporting here is that when I load a YouTube page the play/pause button is in a random state, and this is a bit confusing, especially in the beginning. I hope this can be fixed.

Thanks!

**Comment by Eloston** [comment]
This should be fixed in the new version I'm working on. It'll be more aware of the video players on the page. I should get this out by the end of the week.

**Comment by Eloston** [comment]
Fixed with 1c7222ff22d572de774af5eb1757fadf512d28dc
