### ISSUE TITLE
Twitter.com

### ISSUE THREAD

**Issue by uBlock-user** [Eloston/disable-html5-autoplay#100]
Steps to reproduce
1) Visit - https://twitter.com/TomCruise
2) Scroll back and forth around the twitter feed on the said url and the video will start playing.

Expected outcome - The video won't auto-play.

Actual outcome - videos starts playing as soon as we reach them based on scrolling activity.

**Comment by Eloston** [comment]
It's not autoplaying for me. Do you have Flash? If you don't it's probably some race condition in the code.

**Comment by uBlock-user** [comment]
Well it does for me. Yes I do have flash enabled. Doesn't happen on other sites.

**Comment by Eloston** [comment]
Do you have the same problem if you disable Flash?

**Comment by uBlock-user** [comment]
Yes, no change.

**Comment by Eloston** [comment]
Alright.

**Comment by uBlock-user** [comment]
If it's indeed the bug, then why isn't happening for you ? 

Browser is Chromium 57 with extensions, uBO, HTTPS Everywhere and Disable HTML5 Autoplay

**Comment by Eloston** [comment]
There are some long-standing bugs that happen occasionally to me (or maybe only once), but more often to others. IIRC, some of them I've determined to be race conditions, so I figured that other video players could have the same issue.

**Comment by uBlock-user** [comment]
So how is flash player involved in this? They're two completely different players, so shouldn't they have nothing to race about ?

**Comment by Eloston** [comment]
@uBlock-user Flash player isn't involved in this case. In a number of other cases, people were reporting that some videos autoplayed because they were Flash video players, not HTM5 media players.

**Comment by uBlock-user** [comment]
Ah, understood. Let me know when you fix it.
