### ISSUE TITLE
Provide documentation on Modes and Mode Rules

### ISSUE THREAD

**Issue by merach** [Eloston/disable-html5-autoplay#107]
### Expected behavior
Documentation for Modes and Mode Rules should be available
### Actual behavior
Documentation isn't available in the extension or on the wiki page
### Steps to reproduce the behavior

1. Click the extension button
2. Click "Open options page"
3. Click the hyperlink under Mode Rules List in the line that reads:
Consult the wiki for information on the Mode Rules List: Modes and Mode Rules
This leads to:
https://github.com/Eloston/disable-html5-autoplay/wiki/Modes and Mode Rules

This is not a valid URL. Please review RFC 3986 for proper URL syntax (https://tools.ietf.org/html/rfc3986)

**Comment by Eloston** [comment]
I accidentally deleted the page without realizing. Apparently reverting a change that does nothing deletes the page, or I just misunderstood what GitHub was telling me.
