### ISSUE TITLE
Nothing can be started

### ISSUE THREAD

**Issue by GronbergInfo** [Eloston/disable-html5-autoplay#111]
I cannot make anything play with this extension enabled in Chromium.
Facebook, soundcloud, anything, nothing starts when i press play.

**Comment by Eloston** [comment]
I can assure you that this extension still does work with certain sites and media players. Some other sites require you to press the play/pause button three times before the media will start playing. Others like SoundCloud don't work as reported in other issues here.

If you have specific webpages that are not working and are not already reported here, then please open new issues. Thanks.
