### ISSUE TITLE
[Discussion] Progress of disabling autoplay/autobuffering in Chrome

### ISSUE THREAD

**Issue by uBlock-user** [Eloston/disable-html5-autoplay#118]
Test-case 1 - http://screenrant.com/video/10-deleted-scenes-that-would-have-made-movies-way-better/

Test-case 2 - http://www.theage.com.au/comment/four-ways-they-can-get-rid-of-trump-sooner-rather-than-later-20170130-gu1v28.html

Install Chromium 58 or Chromium 57 to test this.

Before Chromium 58, the video would start auto buffering and playing. I'm on Chromium 58 at the moment and it doesn't buffer or auto-play, it only fetches the player, the thumbnail and the play button, basically imitating click-to-play behavior.

I think this is related to the feature Chromium team introduced in Chromium 57 - https://bugs.chromium.org/p/chromium/issues/detail?id=672086

I haven't tested this on Chromium 57, so feel free to post your own discoveries. @Eloston Can you confirm this ?

New chrome flag has been added apparently - `chrome://flags/#cross-origin-media-playback-requires-user-gesture`

**Comment by Eloston** [comment]
I don't think the feature is related to this because there are no commits or code changes associated with it yet, and its status hasn't been changed to "Started" or anything like that yet.

The behavior you're describing is interesting, though. Does it still play if you click play?

**Comment by uBlock-user** [comment]
Yes, works perfectly on the aformentioned test-cases.

**Comment by Eloston** [comment]
The links you provided are only limited to audio, but it still makes me wonder how they implemented it.

**Comment by uBlock-user** [comment]
Actually they're for videos and with conditional mute on audio to imitate Chrome on Android's behavior where audio is automatically muted.

**Comment by Eloston** [comment]
I think so. I think the features you linked are just for muting audio. They aren't necessarily disabling autoplay and they are probably not disabling autobuffering. Until they figure out some solution, an extension will still be useful.

**Comment by uBlock-user** [comment]
But the flag explicitly is named `cross-origin-media-playback-requires-user-gesture` and it is doing that. Videos pulled thorough Brightcove players are cross origin iframes fetched via XHRs, so it does fall under the defintion of auto play and auto buffer. Also it 's `media-playback` not `audio-playback` which defies what you're saying. Media can be audio or video or both.

**Comment by Eloston** [comment]
Well that's strange, considering how your previous links described the feature. Your reasoning was enough incentive for me to seek the truth, so I skimmed some of the changes. It seems Google already has code that renders my extenion almost useless (see [HTMLMediaElement.cpp](https://chromium.googlesource.com/chromium/src/+/df72ed087b3083bdea9b882bf473f8a9f4dc1276/third_party/WebKit/Source/core/html/HTMLMediaElement.cpp)).

However there are a few differences from Chromium's algorithm to this extension just from looking at HTMLMediaElement.cpp:
* Chromium uses a user gesture instead of trying to disable it automatically. This is not necessarily a bad thing, as my solution would require more convoluted algorithms to detect user actions that may not work any better than it does now. Also, my solution can be circumvented (due to being in JavaScript only)
* Chromium's algorithm may only be operating on video elements, and non-streams. Hopefully they expand it to work on both, though. ([See this function](https://chromium.googlesource.com/chromium/src/+/df72ed087b3083bdea9b882bf473f8a9f4dc1276/third_party/WebKit/Source/core/html/HTMLMediaElement.cpp#3791))
* No per-domain control as I can tell (unless it's done in a function that I didn't look into)
* There seems to be other caveates but I didn't look into them.

But overall, this is great news (or bad news, depending on the perspective).

**Comment by uBlock-user** [comment]
Since all signs are pointing towards what I believe would happen eventually, would it ultimately end up imitating click-to-play feature ?

**Comment by Eloston** [comment]
It's possible, but it most likely won't be similar to the click-to-play for plugins. Many media players overlay elements on top of the media elements that makes this difficult.

**Comment by uBlock-user** [comment]
What about the players that `force` auto-play ? Brightcove and Playwire do it, did you find any code related to that ? They're the ones specifically abusing user-gestures by forcing autoplay via multiple attempts.

**Comment by uBlock-user** [comment]
Test-case 3 - http://9cartoon.me/Watch/11698/the-scooby-doo-show-1976-1978/season-3-episode-4-to-switch-a-witch/

By default it will start playing the video, but if you activate the chrome flag, it won't play or buffer and will leave a warning in the console like this - https://i.gyazo.com/a4d850a14809df424056a10ca82216a5.png

**Comment by Eloston** [comment]
Is this Chrome flag available on the currently stable version 57, or is it only on 58?

**Comment by uBlock-user** [comment]
It is available since v57, however it hasn't made progress as I was expecting. It works for some sites and for some it doesn't.

**Comment by uBlock-user** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=715049

**Comment by Eloston** [comment]
Nice find. It'll be interesting to see how it will turn out in the end. It will be great if it ends the need for extensions related to disabling autoplay.

However, they didn't mention disabling autobuffering in the document. Hopefully they will be considering that too.

Kinda neat that they referenced this extension in the design document.

**Comment by uBlock-user** [comment]
After 4 months, I'm on Chromium 60 now and auto play has been killed for good.

Check the Test case 2 - http://www.theage.com.au/comment/four-ways-they-can-get-rid-of-trump-sooner-rather-than-later-20170130-gu1v28.html

This is how it looks like now - 

![](https://i.gyazo.com/afd9dbcfbf1cc12b367aa33bf40ce591.png)

There is no auto-buffering either. I think it's safe to say that in the next few releases auto-play and buffering will be completely under user's control.

**Comment by Eloston** [comment]
Wow, this is great. How do sites like SoundCloud work in this release? (They use JavaScript to create an orphaned audio element to play audio)

**Comment by uBlock-user** [comment]
You mean soundcloud embedded links ?

**Comment by Eloston** [comment]
No, I'm not talking just about SoundCloud's embedded audio player. I am also taking about the website. I am wondering how they handle autoplay disabling when everything's mostly JavaScript controlled and the audio element doesn't exist in the DOM.

**Comment by uBlock-user** [comment]
Yeah doesn't work there. 

Anyways the work on Unified Autoplay policy is moving swiftly and is aimed for Chromium 61 release.

**Comment by Eloston** [comment]
> Yeah doesn't work there.

Do you mean that just autoplay is stopped, or do you mean it stops autoplay and any attempt to play audio?

> Anyways the work on Unified Autoplay policy is moving swiftly and is aimed for Chromium 61 release.

Nice. I'll probably try it out once that becomes stable.

**Comment by Eloston** [comment]
Progress in Chromium 61 (development build): https://github.com/Eloston/disable-html5-autoplay/issues/175#issuecomment-310805588

**Comment by uBlock-user** [comment]
> Do you mean that just autoplay is stopped, or do you mean it stops autoplay and any attempt to play audio?

No, I meant none of them work there.

@toddwc thanks for sharing your findings.

**Comment by uBlock-user** [comment]
and it works on SC too

Test case - https://soundcloud.com/a-boogie-wit-da-hoodie/drowning-feat-kodak-black-1

**Comment by uBlock-user** [comment]
Unless you click on the play or the spinner button, it will not buffer and play.

**Comment by uBlock-user** [comment]
@toddwc Can you check if it works on facebook ? For me it doesn't.

**Comment by toddwc** [comment]
I've never had any problems on Facebook because it provides a switch to disable autoplay.

Are there other sites we can test that are especially irritating? For me, CNN and USA Today were on the top of the list. I know it works on CNN, but haven't tested USA Today yet. Huffington Post was a problem, too, but I haven't visited there in a while.

**Comment by toddwc** [comment]
It works on USA Today! The only flag option that stops the autoplay is "**Document user activation is required**." When that's activated, you see a still photo instead of a video.

The test URL:

https://www.usatoday.com/story/news/world/2017/06/29/trumps-scaled-back-travel-ban-goes-into-effect-thursday/438523001/

**Comment by uBlock-user** [comment]
> I've never had any problems on Facebook because it provides a switch to disable autoplay.

Yes, that's a server sided option, so switch it ON and test if it overrides your settings because it does and also same behaviour with youtube embedded widgets with autoplay set to 1 via the URL.

**Comment by uBlock-user** [comment]
Also it works on most websites except Facebook, Youtube and such.

**Comment by uBlock-user** [comment]
I'm on Chromium 62 now and from what I have learnt so far, muted autoplay videos will still play albeit without sound, so it's half measure. They simply don't want to patch it completely and give users the full control over autoplay, so whereever you find a muted autoplay video, either you will have with it or use uBlock origin and block the entire thing.

**Comment by Eloston** [comment]
[A Chromium dev has responded to this very concern](https://bugs.chromium.org/p/chromium/issues/detail?id=715049#c21). If what the Chromium dev stated about websites were true, then it would eventually become pointless to disable autoplay if this proposal is fully implemented, since websites would find hacky (albeit clever) ways around them.

Simply stated, Google addressed the annoyance with muting the audio. They plan on addressing the data-conscious users in a different manner that includes more than just media.

As an extension to @uBlock-user's comment, uBlock Origin does specify blocking media elements beyond a customizable size.

**Comment by toddwc** [comment]
Google now has a [design document](https://docs.google.com/document/d/1_278v_plodvgtXSgnEJ0yjZJLg14Ogf-ekAFNymAJoU/edit?usp=sharing) on how it will algorithmically handle autoplaying video that is not muted. From what I've gathered from the document and the source code, this is basically how it will work:

- It will consider how long a user engages with a website's now-non-autoplayed videos, if at all.
- It will consider how often the user visits the website.
- A user must visit a site at least five times before the algorithm begins doing its magic.

**Comment by toddwc** [comment]
> Simply stated, Google addressed the annoyance with muting the audio. 

Google is not itself muting the audio. It's saying that if an autoplaying video IS muted, Chrome will leave that muted video alone.

**Comment by Eloston** [comment]
> Google now has a design document on how it will algorithmically handle autoplaying video that is not muted.

It is quite the algorithm they came up with. I'm still wondering how well it will do in practice, though.

> Google is not itself muting the audio. It's saying that if an autoplaying video IS muted, Chrome will leave that muted video alone.

@toddwc Ah I see; I misread this in my haste. Thanks.

**Comment by uBlock-user** [comment]
@Eloston browsers like FF and Safari have already implemented and offer control over autoplay to the user, Chrome is the only one left now. So they can if they want to, but they won't.

**Comment by uBlock-user** [comment]
Also this https://bugs.chromium.org/p/chromium/issues/detail?id=715049#c26

**Comment by uBlock-user** [comment]
Chrome 61 is out! Autoplay policy is now available via the chrome flag. I wonder if this is the final version or if they will continue this any further.

**Comment by uBlock-user** [comment]
https://blog.chromium.org/2017/09/unified-autoplay.html

Related - https://bugs.chromium.org/p/chromium/issues/detail?id=310450

**Comment by tvierling** [comment]
The autoplay policy mentioned above still allows autoplay in many different circumstances.

There is finally a bug open to provide a global switch which presumably would make use of the existing whitelist currently in chrome://settings/content/sound (to affect all media, not just sound):

https://bugs.chromium.org/p/chromium/issues/detail?id=865551

Feel free to star this one to show interest. (As with all Chromium bugs, if you don't have technical input to provide, please don't add a "me too" or similar comment. Just click the star once you're logged in.)

**Comment by uBlock-user** [comment]
Autoplay is now a part of [Policy Controlled Features](https://github.com/WICG/feature-policy/blob/master/features.md#autoplay) fyi

**Comment by uBlock-user** [comment]
Ultimately this switch got removed and the autoplay blocking in Chromium/chrome is back to being half-assed or at times not working at all. I got rid of Chromium entirely and switched to Firefox, which is the only browser that provides complete control over Autoplay(video and audio) now. Sad to see the entire turn of events for Chromium.

**Comment by xbliss** [comment]
> Ultimately this switch got removed and the autoplay blocking in Chromium/chrome is back to being half-assed or at times not working at all. I got rid of Chromium entirely and switched to Firefox, which is the only browser that provides complete control over Autoplay(video and audio) now. Sad to see the entire turn of events for Chromium.

This is sad. Atleast Chromium folks should not be cowering down to Google's we want to AutoPlay media mandates.

**Comment by uBlock-user** [comment]
> Chromium folks should not be cowering down to Google's we want to AutoPlay media mandates.

There's no Chromium folks, its Google's engineers, Google runs Chromium and has complete control over what and what shouldn't get added to Chromium.

**Comment by stevegilbert23** [comment]
> The autoplay policy mentioned above still allows autoplay in many different circumstances.
> 
> There is finally a bug open to provide a global switch which presumably would make use of the existing whitelist currently in chrome://settings/content/sound (to affect all media, not just sound):
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=865551
> 
> Feel free to star this one to show interest. (As with all Chromium bugs, if you don't have technical input to provide, please don't add a "me too" or similar comment. Just click the star once you're logged in.)

That issue is not publicly accessible.  I get a "permission denied" attempting to view it.
