### ISSUE TITLE
error encountered--details are in the developer console

### ISSUE THREAD

**Issue by n1ugu** [Eloston/disable-html5-autoplay#166]
The icon is grayed out and when I click on it I receive this message: "error encountered.  Details are in the developer console."
Any suggestions on how to fix this?
Thanks

**Comment by Eloston** [comment]
It really depends. What does the developer console show? (You can right-click and click "Inspect", and then go over to the Console tab)

**Comment by n1ugu** [comment]
Thanks for the reply, Eloston.  I uninstalled then reinstalled it and it's now working.  I'll remember your "right click trick" if it happens again.
Have a great day.

**Comment by Eloston** [comment]
Glad to hear it works.
