### ISSUE TITLE
Blocks Hangouts, GotoMeeting and Skype!

### ISSUE THREAD

**Issue by jcoonrod** [Eloston/disable-html5-autoplay#167]
Hello team! This is a wonderful tool BUT it also makes web-based video conferencing sites fail. When using any of these apps, outgoing audio works, income audio is totally blocked, and video grinds to a crawl. When this extension is disabled, everything works fine again.

**Comment by Eloston** [comment]
Hello. This is a limitation of the extension; the workaround is to disable it on these sites via the popup menu.

**Comment by halatmit** [comment]
I'm confirming that I see this issue with hangouts on Google Chrome.

**Comment by Piedone** [comment]
Duplicate of https://github.com/Eloston/disable-html5-autoplay/issues/34.
