### ISSUE TITLE
Disable autoplay on certain websites

### ISSUE THREAD

**Issue by MrCris85** [Eloston/disable-html5-autoplay#171]
Hi.  Your autoplay disabler works great, but I'd like to have more control over which websites I want it applied towards.  For example, I don't want to disable autoplay on YouTube, but I want to disable it on ESPN.

**Comment by Eloston** [comment]
You can toggle autoplay in the popup menu, and it will apply on the current website you're looking at. [See the Wiki for more help with the extension](https://github.com/Eloston/disable-html5-autoplay/wiki). Let me know if you need more clarifications.
