### ISSUE TITLE
can i block videos only on a specific page while leaving other pages with html falsh videos to play?

### ISSUE THREAD

**Issue by rtyes** [Eloston/disable-html5-autoplay#191]
Thanks for taking the time to contribute to Disable HTML5 Autoplay!

BEFORE YOU PROCEED, please read the following: https://github.com/Eloston/disable-html5-autoplay/blob/master/NEWS.md

Also, make sure to have consulted [the Wiki](https://github.com/Eloston/disable-html5-autoplay/wiki) first; especially [the Support page](https://github.com/Eloston/disable-html5-autoplay/wiki/Support)

Please delete the entirety of this message when composing your issue. Thanks again!

**Comment by rtyes** [comment]
i am using the extension to block html 5 flash autoplay videos. My question is can I use this feature on only specific page page on my website while leaving open the option for the videos to autoplay on another page ? Kindly assist me with this anyone please. Very thankful.

**Comment by Eloston** [comment]
It is not possible for this extension to block HTML5 autoplay for specific pages. You can only block from a domain.

This extension does not involve Flash in any way.
