### ISSUE TITLE
USA Today autoplay with autoplay disabled. 

### ISSUE THREAD

**Issue by wlinde** [Eloston/disable-html5-autoplay#192]
The video at this link plays with autoplay enabled. I have used chrome to disable flash as well. 

https://www.usatoday.com/story/news/politics/2017/08/21/secret-service-cant-pay-agents-because-trumps-frequent-travel-large-family/529075001/

**Comment by Dynamic-Gravity** [comment]
Can confirm. Although, for me the video did not play automatically but once I scrolled down then the video went into the bottom right corner and started auto play.

**Comment by Eloston** [comment]
Duplicate of #47
