### ISSUE TITLE
Heavy, intermittent network usage spikes

### ISSUE THREAD

**Issue by tristanbrown** [Eloston/disable-html5-autoplay#222]
Autoplay Blocker seems to sometimes get stuck in a loop where it's sending and receiving huge spikes of data over the network, on a rapid, repeating interval. I've attached an image showing what happened when I had the extension disabled, enabled it, and then disabled it again after about 45 seconds. This was with NO Chrome sites open (just an empty "New Tab"). 

![190530_AutoplayBlocker_WiFi_usage](https://user-images.githubusercontent.com/15306522/58646583-4f2f9080-82cb-11e9-8bbe-1d5b50da8a7d.PNG)

The data usage spikes I was able to capture in the image are smaller than the ones that got me to notice the issue. While I had several sites open in Chrome, Autoplay Blocker was maxing out my network usage at 7.7 mbps, intermittently, every second or so, averaging ~260 kbps usage. These spikes were enough to harm the quality of a video call I was running in Hangouts, and continued even after I closed the video call and all of the other sites I had open in Chrome. It was only after I disabled and re-enabled Autoplay Blocker that the spikes got smaller (as shown in the image above), and they disappeared completely after I opened a site again (gmail, if it matters; I also have Autoplay Blocker set to "Disable Nothing" on gmail and Hangouts). 

This is the third time I've noticed this problem occurring over the past 2 weeks, but I don't know how to trigger it. I only notice it when it starts affecting the quality of my video calls.

**Comment by 3941** [comment]
I noticed the same issue today. Something fishy is going on. I wrote a report to Google. This is what I found and wrote:

"Now, to be fair, I don't exactly know what it does, but it'll constantly communicate with IP 165.22.1.78 on port 8082 and will occasionally send rather large amounts of data to that server.

I found the exact extension that did it by disabling them one by one and using Wireshark.
Whatever it does, I'm pretty sure it's not needed to provide the functionality it advertises.
I didn't wait for another "large data transfer" phase to analyze it more thoroughly. I'd rather not.

Furthermore, this extension is supposedly unmaintained and the code at the github address hasn't seen an update in 3 years, yet this extension got an update last month? Seems very weird.

I checked the code of the extension and it includes a heavily modified jquery-3.3.1.min.js, which also references the web address http://nr-extensions.tk which, unsurprisingly, points at the IP 165.22.1.78...

The code is obfuscated, or minified, and unminifying doesn't make it any more readable to me.
Things are just very, very fishy, so I'd appreciate someone looking into it."

**Comment by 3941** [comment]
Some recent reviews on the chrome store:
https://i.imgur.com/qIfG6MU.png
https://i.imgur.com/F0iEYa8.png

Yeah, stay the fuck away I suppose....

**Comment by Eloston** [comment]
@3941 You don't seem to be looking at the right extension. The correct extension is here (as linked in the README): https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai

Last update is 2017 and I couldn't find any of the reviews you linked. I do not have any other extensions on the CWS at this time.

**Comment by 3941** [comment]
Huh, you're right. The extension I'm talking about is posing as yours, though.
Must be a fork that was then spiced with malware.
I don't suppose the behavior that @tristanbrown describes makes a lot of sense if he's not also talking about this fake extension.
https://chrome.google.com/webstore/detail/html5-autoplay-blocker/icppkihnmgkncknjlfkkjgfgoifkcgii

Anyway, thanks for clearing that up. I did wonder why the extension author had a different name. That's how I thought the hijack happened.

**Comment by Eloston** [comment]
@3941 Huh, thanks for linking that. I'll make a note of it on this repo.
