### ISSUE TITLE
Issue: Spotify doesn't work when the extension is on

### ISSUE THREAD

**Issue by detfusco** [Eloston/disable-html5-autoplay#226]
I tried to pressing pause/play button multiple times but nothing. It only plays if I turn the extension off. Maybe add a whitelist/blacklist option to the extension?

**Comment by orbatschow** [comment]
You can find the feature you're looking for with these steps:

Left-click on the extension icon -> options -> Mode Rules List

Documentation:

https://github.com/Eloston/disable-html5-autoplay/wiki/Modes%20and%20Mode%20Rules
