### ISSUE TITLE
Chrome extension completely disabled, says "malware detected" 

### ISSUE THREAD

**Issue by Prismaria** [Eloston/disable-html5-autoplay#238]
I just received a popup saying Chrome has removed this extension due to malware and now the extension is completely disabled. I can't even manually toggle it on. 

I know the developer has stopped maintaining the extension, but they could at the very least file a dispute against Google's BS claim and put the extension back on the play store.

Or perhaps someone can fork the project and make a new extension. Would be greatly appreciated, thanks.

**Comment by joridiculous** [comment]
I got the same Warning popup and auto disabling, but in Chrome it says: HTML5 Autoplay Blocker 1.50
And clicking "View in Chrome store" returns a 404, clicking links from a search works fine. (https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai)

Newer mind, looks like i got the fake one installed for some reason. (https://github.com/Eloston/disable-html5-autoplay/issues/223)

**Comment by theultramage** [comment]
Damnit, I fell for it as well. The real extension's id starts with 'efdh'. If you have 'icpp' and it's flagged as malware, that's because it likely is. The disabled version from 2020 that I had contains js/businessLogic.js, a 2MB file that appears to be a fully featured crypto library written in javascript, with a bunch of minified crap mixed in.

**Comment by Prismaria** [comment]
> Damnit, I fell for it as well. The real extension's id starts with 'efdh'. If you have 'icpp' and it's flagged as malware, that's because it likely is. The disabled version from 2020 that I had contains js/businessLogic.js, a 2MB file that appears to be a fully featured crypto library written in javascript, with a bunch of minified crap mixed in.

Well shit. Ngl I kinda liked the fake version's icon better, lol.
