### ISSUE TITLE
For Opera Users

### ISSUE THREAD

**Issue by shwetank** [Eloston/disable-html5-autoplay#3]
It would be great if you could submit this extension to the Opera Addons Catalog as well. It accepts crx files as well, so if you want, you can submit this exact same crx extension that you use for the chrome store and submit it to the Opera addons catalog too, so that Opera users can also install it properly from the official channel. 

(I can help you out with the whole process of submitting it to the catalog too, if you want).

**Comment by Eloston** [comment]
I submitted it to Opera Addons just now. When it gets published, it should show up here: https://addons.opera.com/en/extensions/details/disable-html5-autoplay/

**Comment by shwetank** [comment]
The extension is now live on https://addons.opera.com/en/extensions/details/disable-html5-autoplay/

Thanks again!
