### ISSUE TITLE
ScriptBlock Conflict

### ISSUE THREAD

**Issue by adam234** [Eloston/disable-html5-autoplay#32]
repro: visit www.gypsyweb.net with disable autoplay .6.1. Hear music.
expected: no music autoplays
Actual: music plays

**Comment by Eloston** [comment]
I am unable to reproduce the issue. When I go to the website with autoplay disabled, no audio plays and the media statistics update with autoplay attempts. Is your [Chromium/Chrome or Opera version up-to-date](https://github.com/Eloston/disable-html5-autoplay/wiki/Support#i-am-running-an-old-version-of-chrome-or-opera-and-i-encountered-a-problem)?

**Comment by adam234** [comment]
Chrome Version 47.0.2526.73 (64-bit) shows up to date on MacOS 10.11.1.  Also have scriptblock, ghostery, adblock and a couple other privacy plugins.

It doesn't seem inconceivable that there's a hooking conflict. I'd understand if you want to close no-repro, or I'm happy to try to explore combos to see if we can narrow it down.

**Comment by Eloston** [comment]
I just have uBlock Origin and this extension, so your hypothesis seems very likely. If you can figure out which extensions are causing the conflict (and possibly how it conflicts), then I can implement a fix if possible.

**Comment by adam234** [comment]
The issue appears to be scriptblock, https://chrome.google.com/webstore/detail/scriptblock/hcdjknjpbnhdoabbngpmfekaecnpajba 

When I disabled all extensions & turned them on one at a time, that was the one that triggered. Turning off everything but your ext & Scriptblock repros for me.

**Comment by Eloston** [comment]
Unfortunately, I will not be able to fix this problem.

In order for my extension to work, I must inject code into the webpage. There's no way for me to tell ScriptBlock not to block my injected code, so ScriptBlock ends up blocking my code as well.

This extension injects an inline script into the webpage to work. If you want, you can modify `blockStart.js` in ScriptBlock and uncomment the line `// const DO_NOT_MITIGATE_INLINE_SCRIPTS = true;`. However, this will also allow any other inline script on the page to run as well.

**Comment by adam234** [comment]
Thanks for investigating, the conflict seems "reasonable" and I don't have a solution to offer up.
