### ISSUE TITLE
This Extension was disabling webRTC

### ISSUE THREAD

**Issue by danvforbes** [Eloston/disable-html5-autoplay#38]
I enjoy using Blab.im which uses webRTC technology. This extension was blocking the receiving of Video and Audio.

Is there a way to white-list certain web sites or urls to allow video/audio?  I'd like to use the ex to stop videos from playing automatically across web sites I visit.  But, I didn't know it would prevent me from using live video on the site I want to use.

**Comment by Eloston** [comment]
Thanks for letting me know about the website that broke.

Everything you need to know is [already in the Wiki](https://github.com/Eloston/disable-html5-autoplay/wiki/Modes%20and%20Mode%20Rules).
