### ISSUE TITLE
USA Today videos aren't stopped

### ISSUE THREAD

**Issue by twolf2919** [Eloston/disable-html5-autoplay#39]
I actually have no idea whether USA Today uses "HTML5" to play its videos - but they're definitely not stopped by this extension.  Here's a recent example:
http://www.usatoday.com/story/weather/2016/01/20/winter-storm-snow-mid-atlantic-northeast/79048448/

I'm running v.0.6.1 of the plugin and the latest version of Chrome - 47.0.2526.111 on Windows 10.

**Comment by Eloston** [comment]
Thanks for reporting. Do you have Flash player installed? Also, do you use an ad-blocker?

I don't have Flash player, and I use uBlock Origin. When I go to the link with uBlock on, the video won't autoplay regardless of my extension. When uBlock is off, the video won't autoplay when my extension is on.

USA Today could be using Flash if they detect if it's installed. I don't have any Flash-enabled browser right now, so I can't test this.

**Comment by shellster** [comment]
I can confirm that the video isn't autoplaying with the extension in HTML5.  It is being swapped to a flash video in that case.  Enabling Click-To-Play for flash, fixes that problem.

**Comment by Eloston** [comment]
Thanks for confirming @shellster
