### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by LucasD3** [Eloston/disable-html5-autoplay#4]
The new button seems not to be working on my system. At first it appeared in color and autoplay was disabled (as expected). Clicking the button produced no discernible change in appearance or behavior. At some point today the button changed to grey and autoplay became enabled. Now, the button seems to be stuck on grey and clicking it seems to do nothing. And autplay is still enabled.

System: OS 10.10.4, Chrome version 44.0.2403.130 
Extension version: 0.4.1

**Comment by Eloston** [comment]
When I posted version 0.4, I updated the Chrome Webstore description with information regarding this button:
This extension creates an icon next to the address bar (which is called a Browser Action.) The icon has two states:
-When the icon has color, this means there are media elements on the page.
-When the icon is a light grey, this means that no media elements are on the page.
The number that appears on the icon indicates the number of autoplay attempts on the page.

Right now, clicking on the Browser Action does nothing. This will be changed in a future version.

I have updated the GitHub README.md with the new information as well.

**Comment by Eloston** [comment]
I also want to point out one more thing: Until I introduce website whitelisting, autoplay will always be disabled.
When this changes, I'll be sure to update all the descriptions. Anyway, thanks for pointing out changes that I didn't make very clear to the public.

**Comment by LucasD3** [comment]
Okay, sorry for not reading the information properly. However, my confusion arose from the fact that with the new version, HTML 5 videos are autoplaying on many sites. I will post a new issue with details.

**Comment by LucasD3** [comment]
Okay, thanks.  I'm sorry for not reading the information properly.
