### ISSUE TITLE
Not working on a particular youtube URL

### ISSUE THREAD

**Issue by LucasD3** [Eloston/disable-html5-autoplay#5]
On my system, the following youtube video displays in HTML 5 (rather than Flash), and automatically starts playing at about the 3 minute mark. The extension icon appears in color with a the number "1". 

https://www.youtube.com/watch?t=184&v=u4zb6LUehwY

System: Mac OS 10.10.4, Chrome version 44.0.2403.130 
Extension version: 0.4.1

**Comment by Eloston** [comment]
Displaying in HTML5 instead of Flash is a YouTube feature; they prefer HTML5 over Flash.
I tried the video, and it will start playing for a split-second, before pausing. Is this what you mean by autoplaying?

You said in the title that the extension is "Not working on some sites." Can you give me the URLs to the other sites that don't work?

**Comment by LucasD3** [comment]
I have changed the title to clarify that I am only talking about one specific Youtube URL. When I open the link, the video begins playing at about the 3 minute mark and continues playing until the end of the video (in other words, the video plays for about 26 seconds). I consider this a form of autoplaying.

**Comment by Eloston** [comment]
I cannot reproduce this issue on Chromium 43.0.2357.132 on Linux, Chromium 41.0.2272.118 on Windows, and Opera 30.0.1835.125 on Windows. None of my browsers have the Flash plugin installed.
Does this consistently happen on this video at this particular time only, or are there other videos where this will happen?

**Comment by LucasD3** [comment]
So far I have not seen this behavior with any other videos. But it happens every time the same way with the video linked above. I also tried creating a new user profile in Chrome without any other extensions installed, but still the same thing happened.

**Comment by Eloston** [comment]
Under what situations does this happen? For example:
-Opening the URL in a new tab in the background by middle-clicking the URL
-Opening the URL in a new active tab
-Refreshing the page

Also, do you have Opera? If you do, could you test to see if my extension on Opera does the same thing?
Does it autoplay on this video?: https://youtu.be/lSgl4SnQY40?t=10m
If you enter Developer Mode (in chrome://extensions/ by clicking the Developer mode checkbox at the top right) and enable the "Collect errors" checkbox on this extension, do you see any error show up when you visit your URL?

**Comment by 239** [comment]
For me it always starts autoplay this video: [https://youtu.be/xoyNiatRIh4]

**Comment by Eloston** [comment]
@239 What browser version and platform are you using?

**Comment by 239** [comment]
@Eloston Opera 31 on Windows 8.1 and 10 (both 64-bit).

**Comment by Eloston** [comment]
Very interesting. I updated my Opera from 30 to 31 (32 bit on Wine-staging 1.7.48) and installed Google Chrome 44.0.2403.130 (32 bit on Wine-staging 1.7.48). On these versions, all URLs provided here autoplay. It seems that there is a browser-level change that is affecting my extension on the newest Opera and Google Chrome.

**Comment by 239** [comment]
Can also confirm same behaviour with Opera 31 on Manjaro Linux (64-bit).
