### ISSUE TITLE
abcnews.go.com still autoplays

### ISSUE THREAD

**Issue by chrullrich** [Eloston/disable-html5-autoplay#52]
Example: http://abcnews.go.com/Business/overtime-pay-rules-benefit-lower-salary-workers/story?id=39193676

Media elements: 0
Autoplay attempts: 0
Media players: (None recorded)

**Comment by Eloston** [comment]
I'm not able to get this video to autoplay, even with extensions disabled. Can you confirm this is HTML5 video? Try disabling Flash player.

**Comment by chrullrich** [comment]
It seems you're right. Somehow, Flash was on, even though I usually keep it off. With it disabled, I cannot get the thing to play now either. I cannot swear that Flash was on on Wednesday, but it looks like it must have been.

Sorry for the noise.
