### ISSUE TITLE
Extension breaks WebRTC

### ISSUE THREAD

**Issue by legovini** [Eloston/disable-html5-autoplay#55]
Unfortunately this very useful extension breaks WebRTC. This is easy to reproduce, just go here:

https://janus.conf.meetecho.com/echotest.html

and try the echo test. The "Remote Stream" video will not start and there no "play" button to enable it. Allowing videos to autoplay fixes the issue.

**Comment by Eloston** [comment]
This looks like a duplicate of #34.

**Comment by legovini** [comment]
Agreed, sorry for the duplicate, I didn't spot the original report.
Looking forward to see #16 done. Thank you!
