### ISSUE TITLE
Breaks Google Voice

### ISSUE THREAD

**Issue by harve2000** [Eloston/disable-html5-autoplay#56]
Clicking the play button to listen to a recorded message does nothing when this extension is enabled. Is there a way to allow the url of https://www.google.com/voice/ to play recorded messages without me having to disable the extension entirely? This issue is repeatable in Google Chrome Version 51.0.2704.84 (64-bit) under Ubuntu 14.04 LTS.

**Comment by Eloston** [comment]
No, there's no way to do that yet. It looks like you want #51 to be implemented, so I'll close this.
