### ISSUE TITLE
Not working for multiple sites

### ISSUE THREAD

**Issue by mikercrawford** [Eloston/disable-html5-autoplay#6]
http://www.pcworld.com/article/2922403/how-to-stop-autoplaying-html5-videos.html and http://money.cnn.com/2015/08/06/news/companies/cvs-viagra/index.html?sr=fbmoney080615CVS1030story both had autoplay videos that were not stopped by the plugin.

**Comment by Eloston** [comment]
The PCWorld one was fixed in e95bdeb0ad9fa6b915a4d4650fc2e133cc63d95e. I am looking into the other article right now.
