### ISSUE TITLE
Autoplay still occurs on this page

### ISSUE THREAD

**Issue by 00madz** [Eloston/disable-html5-autoplay#70]
It's a bit ironic, but the ad on this page still autoplays for me:
http://www.pcworld.com/article/2858421/internet/how-to-stop-autoplay-videos.html
This is the html tag of the video that is still playing (this is on chrome osx):
`<video title="How to search Gmail with advanced operators" id="bcplayer-rightrail_html5_api" data-account="2522903525001" data-player="c7a504ec-dcd6-4683-80bd-4573a520855b" data-embed="default" data-video-id="ref:65876" class="vjs-tech" src="blob:http%3A//www.pcworld.com/dee7a6fe-20df-4be8-b061-dbec714ec456"></video>`

**Comment by Eloston** [comment]
Yeah that's actually what I have in the code already. I'll publish a new minor release with that fixed.
