### ISSUE TITLE
Can't stop auto loading/buffering, background loading.

### ISSUE THREAD

**Issue by lovebdsobuj** [Eloston/disable-html5-autoplay#78]
This plugin just stop autoplay, but can't stop auto loading/buffering, background loading.

**Comment by Eloston** [comment]
This has been requested in #9.

Closing as a duplicate.

**Comment by lovebdsobuj** [comment]
You can take this addon as model.
[FlashStoper](https://addons.mozilla.org/en-GB/firefox/addon/flashstopper/) for Firefox working good. But FlashStoper don't have chrome extensions.

**Comment by Eloston** [comment]
This is the first time I've heard about FlashStopper. Looks interesting. Thanks

**Comment by lovebdsobuj** [comment]
I will be glad if you implement this feature.
I think, just not only me, many of user expect this feature.
