### ISSUE TITLE
Option to ignore file:// locations

### ISSUE THREAD

**Issue by szborows** [Eloston/disable-html5-autoplay#83]
... either by understanding rules starting with `file://` or adding possibility to ignore whole schemes.

**Comment by Eloston** [comment]
If you enable `Developer mode`, you should have an option to toggle `Allow access to file:/// URLs`. Is this what you wanted?

**Comment by szborows** [comment]
Yes.
And besides that it made me realize how insecure it would be if it was enabled by default. Thanks!
