### ISSUE TITLE
Hulu Videos Blocked / Store Domain Exception

### ISSUE THREAD

**Issue by jojoLvy** [Eloston/disable-html5-autoplay#84]
Hulu videos are prevented from running with the Autoplay blocker on.
Stopping Autoplay  blocker (Disable Nothing) will run Hulu.

If there was a way to store exceptions by domain so It did not need to be stopped each time I try and watch Hulu, that would be a good solution.

Running on Windows 8.1

**Comment by Eloston** [comment]
You can configure settings per-domain via the pop-up menu or the options page. Changing the popu-up setting on a page will set it for the current domain. The Wiki page should have all the information you need.
