### ISSUE TITLE
USA Today videos still autoplay

### ISSUE THREAD

**Issue by bconway** [Eloston/disable-html5-autoplay#91]
Greetings! With the default block setting, the video here still autoplays:

http://www.usatoday.com/story/news/nation/2016/10/29/ag-lynch-objected-fbi-director-going-public-email-review/92949970/

The only other extension I use is uBlock Origin. Thanks.

**Comment by Eloston** [comment]
Thanks for reporting. I will add this link to the pre-existing issue report.

Closing as duplicate of #47.

**Comment by bconway** [comment]
Apologies, should've searched.
