### ISSUE TITLE
How do I allow certain sites to autoplay?

### ISSUE THREAD

**Issue by boydfink** [Eloston/disable-html5-autoplay#95]
I would like to autoplay certain videos (i.e., YouTube). I am only asking to disable the videos which I didn't intend to watch. Any way to allow videos to play automatically on YouTube.com?

**Comment by Eloston** [comment]
There's no control on a per-page basis yet; it can only be done at the domain level for now. FYI, this feature has been requested in #51, so you can keep track of progress there.

**Comment by Poppinjay42** [comment]
So how do I do this at the domain level?  Several sites just do not work at all with this enabled.

Thanks,

FC
