### ISSUE TITLE
Embedded Soundcloud blocked completely

### ISSUE THREAD

**Issue by alexandrulesi** [Eloston/disable-html5-autoplay#99]
Hello,

take this link as reference:

http://www.mixesdb.com/w/2016-01-21_-_Detroit_Swindle_-_Deep_House_Amsterdam_Mixtape_187

The embedded soundcloud player won't start playing at all, no matter how many times I hit play, as long as the plugin is active. Once deactivated the player runs normally. Furthermore the plugin doesn't display any blocking: 0 Media attempts, 0 autoplay attempts.

Platform: OS X El Capita, Chrome

**Comment by Eloston** [comment]
Thanks for reporting. Seems related to #18, so going to mark this as a duplicate.
